# Generated by Django 5.1.1 on 2024-09-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.TextField()),
                ('data_voo', models.DateField()),
                ('valor_passagem', models.IntegerField()),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companhia')),
            ],
        ),
    ]
